### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by lanzone1** [NickSpencer511/Seers-CMP-Cookie-Consent-Banner#1]
When reviewing your template we've noticed that it is using user-defined parameters to build a URL. It's best practice to use [encodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [encodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

The line in question is:
```js
const url = sourceUrl + "?param=" + dataKey;
```

Also, when you make your change, be sure to update the `sha` value in `metadata.yaml` to match.

**Comment by NickSpencer511** [comment]
Hi Andy,

We just updated our code, can you please review again and publish our
template.
 We are greatly thankful for your support.

**Comment by NickSpencer511** [comment]
Hi Andy,

I hope you are doing well.

We would like to express our sincere gratitude for taking the time to
review our code.

Following the review, we are eager to move forward. Could you please advise
us on the next steps required to ensure Seers is visible on template
gallery? Additionally, if possible, we would be grateful for an estimated
timeframe on when Seers might be visible on template gallery.

Thank you again for your assistance. We look forward to your reply.

**Comment by NickSpencer511** [comment]
Hi Andy,

I hope you're doing well.

We would like to update you that we have made *new upgrades* to the Seers
GTM template and have now pushed it live. We are keen to move forward and
would appreciate your guidance on the next steps to ensure Seers is visible
in the template gallery.

Additionally, if possible, could you provide an estimated timeframe for
when Seers updated version might appear in the gallery?

Thank you again for your continued support. We look forward to your
response.

**Comment by lanzone1** [comment]
Hi Nick,

It usually takes a day or two for the template updates to appear in the gallery. See the [developer docs](https://developers.google.com/tag-platform/tag-manager/templates/gallery#update_your_template) for more details about updating templates.

Thanks.

**Comment by NickSpencer511** [comment]
Thank you for your reply. I’ve checked the GTM gallery and I see that the "Last Updated" date has indeed been updated to February 12, 2025. However, when I check the version of the code in the gallery, it still shows the older version (c57a2) instead of the latest one, which I believe should be linked to the new SHA (4e06bfff2783e62fec758803d9cc99591763f822) as reflected in my metadata.yaml.

The change I made, noted in the metadata (changeNotes: Google Consent Mode Updation), doesn't appear to be reflected in the gallery version. Could you assist me in ensuring that the new code version is properly updated in the gallery, or let me know if there’s something I might be missing in the update process?

Thanks in advance for your help!

**Comment by lanzone1** [comment]
Hi Nick,

Looking into this more, your template is not being loaded because it has a parse error. The string `"Advertisement Cookies"` needs to be escaped `\"Advertisement Cookies\"`.

You can test your template by manually importing the TPL file in Tag Manager and ensuring it loads.

Thanks.
